.PHONY: all
all: lint test

.PHONY: test
test:
	pytest tests/

.PHONY: test_incr
test_incr:
	pytest tests/ --testmon --no-cov -n 0

.PHONY: lint
lint:
	flake8 .
	./commit_lint.sh

.PHONY: format
format:
	isort .
	black .

all: clean dist

clean:
	python setup.py clean --all
	rm -rf dist build

build:
	python setup.py build

tar_dist:
	python setup.py sdist

reinstall:
	which gmail-nexus && pip uninstall -y gmail-nexus || echo "no gmail-api-wrapper found"
	pip install .

whl_dist:
	python setup.py bdist_wheel -d dist/

publish: clean whl_dist
	twine upload dist/*

.PHONY: clean build dist all whl_dist reinstall

.PHONY: help
help:
	@echo "Usage:"
	@echo "  make"
	@echo "  	Run flake8 & pytest"
	@echo "  make test"
	@echo "  	Run pytest & output coverage results"
	@echo "  make test_incr"
	@echo "  	Run only tests with recent changes (speedup!)"
	@echo "  make lint"
	@echo "  	Run the flake8 linter"
	@echo "  make format"
	@echo "  	Auto-format Python code"
	@echo "  make package"
	@echo "  	Build the package and upload it to SIL's Pip Registry"
	@echo "  make clean"
	@echo "  	Remove autogenerated files like __py_cache__"
	@echo "  make help"
	@echo "  	Display usage information"

